config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @answer = params[:answer]
    if params[:answer] == 'I am going to work'
      @answer = 'Great'
    elsif params[:answer].include?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="container">
    <h1>Stupid Coaching</h1>
    <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="quest">
  <h2><em>You</em></h2>
  <p><%= params[:answer] %></p>
</div>
<div class="ans">
  <h2><em>Your Coach</em></h2>
  <p><%= @answer %></p>
</div>
<br>
<%= link_to 'Ask a new question', ask_path  %>

app/views/questions/ask.html.erb
<form action="answer" method="get">
  <input type="text" name="answer" value="<%= params[:answer] %>">
  <input type="submit" value="Ask!">
</form>